### ISSUE TITLE
Criar todo fluxo de agendamento ***

### ISSUE THREAD

**Issue by HaissamHammoud** [Rafa-KozAnd/Projeto_Monitoria_App#34]
Nesse fluxo do backend deve conter:
- [ ] O aluno deve poder agendar um horario com a monitoria
- [ ] O monitor deve poder aprovar ou não aprovar um agendamento
- [ ] O aluno deve poder canselar um agendamento feito por ele
- [ ] O monitor deve poder visualizar todos os seus agendamentos
- [ ] O aluno deve poder visualizar todos os seus agendamentos

Talvez seja uma boa ideia criar algum script de teste neste caso. para garanti que vai estar funcionadno no dia do nosso tcc

**Comment by HaissamHammoud** [comment]
Produzir uma ferramenta onde os alunos interessados em receber ajuda de monitoria tenham acesso aos monitores disponíveis para as disciplinas e suas respectivas agendas.
